[metadata]
name = atrex
version = 0.2.0
description = Alibaba TensoR Engine for heterogeneous devices (X)
author = Alibaba
author_email = atrex@alibaba-inc.com
license = Apache-2.0

[options]
packages = find:
package_dir =
    = python
include_package_data = True
python_requires = >=3.10

[options.packages.find]
where = python
include = atrex*
